name: "Semgrep SAST Scan"

on:
  push:
    branches:
      - main
      - canary
  pull_request:
    branches:
      - main
      - canary
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    name: "Scan Codebase"
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
      contents: read
      actions: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/owasp-top-ten
